apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-tekton-fundamentals
spec:
  vendor: eduk8s.io
  title: Tekton Fundamentals
  description: Workshop on learning the fundamentals of using Tekton for CI/CD
  url: https://github.com/eduk8s-tests/lab-tekton-fundamentals-short
  tags:
  - containers
  - builds
  - tools
  content:
    image: quay.io/eduk8s-tests/lab-tekton-fundamentals-short:latest
  duration: 45m
  session:
    budget: xlarge
    applications:
      console:
        enabled: false
      terminal:
        enabled: true
        layout: split
      registry:
        enabled: true
        memory: 350Mi
    objects:
    - apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: tekton-sa
      secrets:
      - name: registry-credentials
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        name: create-deployments-services
      rules:
      - apiGroups: ["apps", ""]
        resources: ["deployments", "deployments.apps", "services"]
        verbs: ["get", "create", "update", "patch"]
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: create-deployments-services-binding
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: Role
        name: create-deployments-services
      subjects:
      - kind: ServiceAccount
        name: tekton-sa
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: privileged-role-binding
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: vmware-system-tmc-psp-privileged
      subjects:
      - kind: ServiceAccount
        name: tekton-sa
        namespace: $(session_namespace)
